// Static hero name / shortname mapping.
// Source: https://api.opendota.com/api/heroes — kept as a small static file
// to avoid runtime API dependency on hero metadata.
// Update periodically as new heroes are added.

export const HEROES: Record<number, { displayName: string; shortName: string }> = {
  1: { displayName: "Anti-Mage", shortName: "antimage" },
  2: { displayName: "Axe", shortName: "axe" },
  3: { displayName: "Bane", shortName: "bane" },
  4: { displayName: "Bloodseeker", shortName: "bloodseeker" },
  5: { displayName: "Crystal Maiden", shortName: "crystal_maiden" },
  6: { displayName: "Drow Ranger", shortName: "drow_ranger" },
  7: { displayName: "Earthshaker", shortName: "earthshaker" },
  8: { displayName: "Juggernaut", shortName: "juggernaut" },
  9: { displayName: "Mirana", shortName: "mirana" },
  10: { displayName: "Morphling", shortName: "morphling" },
  11: { displayName: "Shadow Fiend", shortName: "nevermore" },
  12: { displayName: "Phantom Lancer", shortName: "phantom_lancer" },
  13: { displayName: "Puck", shortName: "puck" },
  14: { displayName: "Pudge", shortName: "pudge" },
  15: { displayName: "Razor", shortName: "razor" },
  16: { displayName: "Sand King", shortName: "sand_king" },
  17: { displayName: "Storm Spirit", shortName: "storm_spirit" },
  18: { displayName: "Sven", shortName: "sven" },
  19: { displayName: "Tiny", shortName: "tiny" },
  20: { displayName: "Vengeful Spirit", shortName: "vengefulspirit" },
  21: { displayName: "Windranger", shortName: "windrunner" },
  22: { displayName: "Zeus", shortName: "zuus" },
  23: { displayName: "Kunkka", shortName: "kunkka" },
  25: { displayName: "Lina", shortName: "lina" },
  26: { displayName: "Lion", shortName: "lion" },
  27: { displayName: "Shadow Shaman", shortName: "shadow_shaman" },
  28: { displayName: "Slardar", shortName: "slardar" },
  29: { displayName: "Tidehunter", shortName: "tidehunter" },
  30: { displayName: "Witch Doctor", shortName: "witch_doctor" },
  31: { displayName: "Lich", shortName: "lich" },
  32: { displayName: "Riki", shortName: "riki" },
  33: { displayName: "Enigma", shortName: "enigma" },
  34: { displayName: "Tinker", shortName: "tinker" },
  35: { displayName: "Sniper", shortName: "sniper" },
  36: { displayName: "Necrophos", shortName: "necrolyte" },
  37: { displayName: "Warlock", shortName: "warlock" },
  38: { displayName: "Beastmaster", shortName: "beastmaster" },
  39: { displayName: "Queen of Pain", shortName: "queenofpain" },
  40: { displayName: "Venomancer", shortName: "venomancer" },
  41: { displayName: "Faceless Void", shortName: "faceless_void" },
  42: { displayName: "Wraith King", shortName: "skeleton_king" },
  43: { displayName: "Death Prophet", shortName: "death_prophet" },
  44: { displayName: "Phantom Assassin", shortName: "phantom_assassin" },
  45: { displayName: "Pugna", shortName: "pugna" },
  46: { displayName: "Templar Assassin", shortName: "templar_assassin" },
  47: { displayName: "Viper", shortName: "viper" },
  48: { displayName: "Luna", shortName: "luna" },
  49: { displayName: "Dragon Knight", shortName: "dragon_knight" },
  50: { displayName: "Dazzle", shortName: "dazzle" },
  51: { displayName: "Clockwerk", shortName: "rattletrap" },
  52: { displayName: "Leshrac", shortName: "leshrac" },
  53: { displayName: "Nature's Prophet", shortName: "furion" },
  54: { displayName: "Lifestealer", shortName: "life_stealer" },
  55: { displayName: "Dark Seer", shortName: "dark_seer" },
  56: { displayName: "Clinkz", shortName: "clinkz" },
  57: { displayName: "Omniknight", shortName: "omniknight" },
  58: { displayName: "Enchantress", shortName: "enchantress" },
  59: { displayName: "Huskar", shortName: "huskar" },
  60: { displayName: "Night Stalker", shortName: "night_stalker" },
  61: { displayName: "Broodmother", shortName: "broodmother" },
  62: { displayName: "Bounty Hunter", shortName: "bounty_hunter" },
  63: { displayName: "Weaver", shortName: "weaver" },
  64: { displayName: "Jakiro", shortName: "jakiro" },
  65: { displayName: "Batrider", shortName: "batrider" },
  66: { displayName: "Chen", shortName: "chen" },
  67: { displayName: "Spectre", shortName: "spectre" },
  68: { displayName: "Ancient Apparition", shortName: "ancient_apparition" },
  69: { displayName: "Doom", shortName: "doom_bringer" },
  70: { displayName: "Ursa", shortName: "ursa" },
  71: { displayName: "Spirit Breaker", shortName: "spirit_breaker" },
  72: { displayName: "Gyrocopter", shortName: "gyrocopter" },
  73: { displayName: "Alchemist", shortName: "alchemist" },
  74: { displayName: "Invoker", shortName: "invoker" },
  75: { displayName: "Silencer", shortName: "silencer" },
  76: { displayName: "Outworld Destroyer", shortName: "obsidian_destroyer" },
  77: { displayName: "Lycan", shortName: "lycan" },
  78: { displayName: "Brewmaster", shortName: "brewmaster" },
  79: { displayName: "Shadow Demon", shortName: "shadow_demon" },
  80: { displayName: "Lone Druid", shortName: "lone_druid" },
  81: { displayName: "Chaos Knight", shortName: "chaos_knight" },
  82: { displayName: "Meepo", shortName: "meepo" },
  83: { displayName: "Treant Protector", shortName: "treant" },
  84: { displayName: "Ogre Magi", shortName: "ogre_magi" },
  85: { displayName: "Undying", shortName: "undying" },
  86: { displayName: "Rubick", shortName: "rubick" },
  87: { displayName: "Disruptor", shortName: "disruptor" },
  88: { displayName: "Nyx Assassin", shortName: "nyx_assassin" },
  89: { displayName: "Naga Siren", shortName: "naga_siren" },
  90: { displayName: "Keeper of the Light", shortName: "keeper_of_the_light" },
  91: { displayName: "Io", shortName: "wisp" },
  92: { displayName: "Visage", shortName: "visage" },
  93: { displayName: "Slark", shortName: "slark" },
  94: { displayName: "Medusa", shortName: "medusa" },
  95: { displayName: "Troll Warlord", shortName: "troll_warlord" },
  96: { displayName: "Centaur Warrunner", shortName: "centaur" },
  97: { displayName: "Magnus", shortName: "magnataur" },
  98: { displayName: "Timbersaw", shortName: "shredder" },
  99: { displayName: "Bristleback", shortName: "bristleback" },
  100: { displayName: "Tusk", shortName: "tusk" },
  101: { displayName: "Skywrath Mage", shortName: "skywrath_mage" },
  102: { displayName: "Abaddon", shortName: "abaddon" },
  103: { displayName: "Elder Titan", shortName: "elder_titan" },
  104: { displayName: "Legion Commander", shortName: "legion_commander" },
  105: { displayName: "Techies", shortName: "techies" },
  106: { displayName: "Ember Spirit", shortName: "ember_spirit" },
  107: { displayName: "Earth Spirit", shortName: "earth_spirit" },
  108: { displayName: "Underlord", shortName: "abyssal_underlord" },
  109: { displayName: "Terrorblade", shortName: "terrorblade" },
  110: { displayName: "Phoenix", shortName: "phoenix" },
  111: { displayName: "Oracle", shortName: "oracle" },
  112: { displayName: "Winter Wyvern", shortName: "winter_wyvern" },
  113: { displayName: "Arc Warden", shortName: "arc_warden" },
  114: { displayName: "Monkey King", shortName: "monkey_king" },
  119: { displayName: "Dark Willow", shortName: "dark_willow" },
  120: { displayName: "Pangolier", shortName: "pangolier" },
  121: { displayName: "Grimstroke", shortName: "grimstroke" },
  123: { displayName: "Hoodwink", shortName: "hoodwink" },
  126: { displayName: "Void Spirit", shortName: "void_spirit" },
  128: { displayName: "Snapfire", shortName: "snapfire" },
  129: { displayName: "Mars", shortName: "mars" },
  131: { displayName: "Ringmaster", shortName: "ringmaster" },
  135: { displayName: "Dawnbreaker", shortName: "dawnbreaker" },
  136: { displayName: "Marci", shortName: "marci" },
  137: { displayName: "Primal Beast", shortName: "primal_beast" },
  138: { displayName: "Muerta", shortName: "muerta" },
  145: { displayName: "Kez", shortName: "kez" },
  155: { displayName: "Largo", shortName: "largo" },
};

export function getHeroName(heroId: number): string {
  return HEROES[heroId]?.displayName ?? `Hero #${heroId}`;
}

export function getHeroShortName(heroId: number): string {
  return HEROES[heroId]?.shortName ?? `hero_${heroId}`;
}

export function heroIconUrl(heroId: number): string {
  const shortName = getHeroShortName(heroId);
  return `https://cdn.stratz.com/images/dota2/heroes/${shortName}_icon.png`;
}

export function heroBannerUrl(heroId: number): string {
  const shortName = getHeroShortName(heroId);
  return `https://cdn.stratz.com/images/dota2/heroes/${shortName}_vert.png`;
}
