// Static item id -> name mapping.
// Source: STRATZ GraphQL `constants { items }` — kept as a small static file
// to avoid a runtime API dependency on item metadata.
// Update periodically as new items are added.

export const ITEMS: Record<number, { displayName: string; shortName: string }> = {
  1: { displayName: "Blink", shortName: "blink" },
  2: { displayName: "Blades Of Attack", shortName: "blades_of_attack" },
  3: { displayName: "Broadsword", shortName: "broadsword" },
  4: { displayName: "Chainmail", shortName: "chainmail" },
  5: { displayName: "Claymore", shortName: "claymore" },
  6: { displayName: "Helm Of Iron Will", shortName: "helm_of_iron_will" },
  7: { displayName: "Javelin", shortName: "javelin" },
  8: { displayName: "Mithril Hammer", shortName: "mithril_hammer" },
  9: { displayName: "Platemail", shortName: "platemail" },
  10: { displayName: "Quarterstaff", shortName: "quarterstaff" },
  11: { displayName: "Quelling Blade", shortName: "quelling_blade" },
  12: { displayName: "Ring Of Protection", shortName: "ring_of_protection" },
  13: { displayName: "Gauntlets", shortName: "gauntlets" },
  14: { displayName: "Slippers", shortName: "slippers" },
  15: { displayName: "Mantle", shortName: "mantle" },
  16: { displayName: "Branches", shortName: "branches" },
  17: { displayName: "Belt Of Strength", shortName: "belt_of_strength" },
  18: { displayName: "Boots Of Elves", shortName: "boots_of_elves" },
  19: { displayName: "Robe", shortName: "robe" },
  20: { displayName: "Circlet", shortName: "circlet" },
  21: { displayName: "Ogre Axe", shortName: "ogre_axe" },
  22: { displayName: "Blade Of Alacrity", shortName: "blade_of_alacrity" },
  23: { displayName: "Staff Of Wizardry", shortName: "staff_of_wizardry" },
  24: { displayName: "Ultimate Orb", shortName: "ultimate_orb" },
  25: { displayName: "Gloves", shortName: "gloves" },
  26: { displayName: "Lifesteal", shortName: "lifesteal" },
  27: { displayName: "Ring Of Regen", shortName: "ring_of_regen" },
  28: { displayName: "Sobi Mask", shortName: "sobi_mask" },
  29: { displayName: "Boots", shortName: "boots" },
  30: { displayName: "Gem", shortName: "gem" },
  31: { displayName: "Cloak", shortName: "cloak" },
  32: { displayName: "Talisman Of Evasion", shortName: "talisman_of_evasion" },
  33: { displayName: "Cheese", shortName: "cheese" },
  34: { displayName: "Magic Stick", shortName: "magic_stick" },
  35: { displayName: "Recipe Magic Wand", shortName: "recipe_magic_wand" },
  36: { displayName: "Magic Wand", shortName: "magic_wand" },
  37: { displayName: "Ghost", shortName: "ghost" },
  38: { displayName: "Clarity", shortName: "clarity" },
  39: { displayName: "Flask", shortName: "flask" },
  40: { displayName: "Dust", shortName: "dust" },
  41: { displayName: "Bottle", shortName: "bottle" },
  42: { displayName: "Ward Observer", shortName: "ward_observer" },
  43: { displayName: "Ward Sentry", shortName: "ward_sentry" },
  44: { displayName: "Tango", shortName: "tango" },
  45: { displayName: "Courier", shortName: "courier" },
  46: { displayName: "Tpscroll", shortName: "tpscroll" },
  47: { displayName: "Recipe Travel Boots", shortName: "recipe_travel_boots" },
  48: { displayName: "Travel Boots", shortName: "travel_boots" },
  49: { displayName: "Recipe Phase Boots", shortName: "recipe_phase_boots" },
  50: { displayName: "Phase Boots", shortName: "phase_boots" },
  51: { displayName: "Demon Edge", shortName: "demon_edge" },
  52: { displayName: "Eagle", shortName: "eagle" },
  53: { displayName: "Reaver", shortName: "reaver" },
  54: { displayName: "Relic", shortName: "relic" },
  55: { displayName: "Hyperstone", shortName: "hyperstone" },
  56: { displayName: "Ring Of Health", shortName: "ring_of_health" },
  57: { displayName: "Void Stone", shortName: "void_stone" },
  58: { displayName: "Mystic Staff", shortName: "mystic_staff" },
  59: { displayName: "Energy Booster", shortName: "energy_booster" },
  60: { displayName: "Point Booster", shortName: "point_booster" },
  61: { displayName: "Vitality Booster", shortName: "vitality_booster" },
  62: { displayName: "Recipe Power Treads", shortName: "recipe_power_treads" },
  63: { displayName: "Power Treads", shortName: "power_treads" },
  64: { displayName: "Recipe Hand Of Midas", shortName: "recipe_hand_of_midas" },
  65: { displayName: "Hand Of Midas", shortName: "hand_of_midas" },
  66: { displayName: "Recipe Oblivion Staff", shortName: "recipe_oblivion_staff" },
  67: { displayName: "Oblivion Staff", shortName: "oblivion_staff" },
  68: { displayName: "Recipe Pers", shortName: "recipe_pers" },
  69: { displayName: "Pers", shortName: "pers" },
  70: { displayName: "Recipe Poor Mans Shield", shortName: "recipe_poor_mans_shield" },
  71: { displayName: "Poor Mans Shield", shortName: "poor_mans_shield" },
  72: { displayName: "Recipe Bracer", shortName: "recipe_bracer" },
  73: { displayName: "Bracer", shortName: "bracer" },
  74: { displayName: "Recipe Wraith Band", shortName: "recipe_wraith_band" },
  75: { displayName: "Wraith Band", shortName: "wraith_band" },
  76: { displayName: "Recipe Null Talisman", shortName: "recipe_null_talisman" },
  77: { displayName: "Null Talisman", shortName: "null_talisman" },
  78: { displayName: "Recipe Mekansm", shortName: "recipe_mekansm" },
  79: { displayName: "Mekansm", shortName: "mekansm" },
  80: { displayName: "Recipe Vladmir", shortName: "recipe_vladmir" },
  81: { displayName: "Vladmir", shortName: "vladmir" },
  84: { displayName: "Flying Courier", shortName: "flying_courier" },
  85: { displayName: "Recipe Buckler", shortName: "recipe_buckler" },
  86: { displayName: "Buckler", shortName: "buckler" },
  87: { displayName: "Recipe Ring Of Basilius", shortName: "recipe_ring_of_basilius" },
  88: { displayName: "Ring Of Basilius", shortName: "ring_of_basilius" },
  89: { displayName: "Recipe Pipe", shortName: "recipe_pipe" },
  90: { displayName: "Pipe", shortName: "pipe" },
  91: { displayName: "Recipe Urn Of Shadows", shortName: "recipe_urn_of_shadows" },
  92: { displayName: "Urn Of Shadows", shortName: "urn_of_shadows" },
  93: { displayName: "Recipe Headdress", shortName: "recipe_headdress" },
  94: { displayName: "Headdress", shortName: "headdress" },
  95: { displayName: "Recipe Sheepstick", shortName: "recipe_sheepstick" },
  96: { displayName: "Sheepstick", shortName: "sheepstick" },
  97: { displayName: "Recipe Orchid", shortName: "recipe_orchid" },
  98: { displayName: "Orchid", shortName: "orchid" },
  99: { displayName: "Recipe Cyclone", shortName: "recipe_cyclone" },
  100: { displayName: "Cyclone", shortName: "cyclone" },
  101: { displayName: "Recipe Force Staff", shortName: "recipe_force_staff" },
  102: { displayName: "Force Staff", shortName: "force_staff" },
  103: { displayName: "Recipe Dagon", shortName: "recipe_dagon" },
  104: { displayName: "Dagon", shortName: "dagon" },
  105: { displayName: "Recipe Necronomicon", shortName: "recipe_necronomicon" },
  106: { displayName: "Necronomicon", shortName: "necronomicon" },
  107: { displayName: "Recipe Ultimate Scepter", shortName: "recipe_ultimate_scepter" },
  108: { displayName: "Ultimate Scepter", shortName: "ultimate_scepter" },
  109: { displayName: "Recipe Refresher", shortName: "recipe_refresher" },
  110: { displayName: "Refresher", shortName: "refresher" },
  111: { displayName: "Recipe Assault", shortName: "recipe_assault" },
  112: { displayName: "Assault", shortName: "assault" },
  113: { displayName: "Recipe Heart", shortName: "recipe_heart" },
  114: { displayName: "Heart", shortName: "heart" },
  115: { displayName: "Recipe Black King Bar", shortName: "recipe_black_king_bar" },
  116: { displayName: "Black King Bar", shortName: "black_king_bar" },
  117: { displayName: "Aegis", shortName: "aegis" },
  118: { displayName: "Recipe Shivas Guard", shortName: "recipe_shivas_guard" },
  119: { displayName: "Shivas Guard", shortName: "shivas_guard" },
  120: { displayName: "Recipe Bloodstone", shortName: "recipe_bloodstone" },
  121: { displayName: "Bloodstone", shortName: "bloodstone" },
  122: { displayName: "Recipe Sphere", shortName: "recipe_sphere" },
  123: { displayName: "Sphere", shortName: "sphere" },
  124: { displayName: "Recipe Vanguard", shortName: "recipe_vanguard" },
  125: { displayName: "Vanguard", shortName: "vanguard" },
  126: { displayName: "Recipe Blade Mail", shortName: "recipe_blade_mail" },
  127: { displayName: "Blade Mail", shortName: "blade_mail" },
  128: { displayName: "Recipe Soul Booster", shortName: "recipe_soul_booster" },
  129: { displayName: "Soul Booster", shortName: "soul_booster" },
  130: { displayName: "Recipe Hood Of Defiance", shortName: "recipe_hood_of_defiance" },
  131: { displayName: "Hood Of Defiance", shortName: "hood_of_defiance" },
  132: { displayName: "Recipe Rapier", shortName: "recipe_rapier" },
  133: { displayName: "Rapier", shortName: "rapier" },
  134: { displayName: "Recipe Monkey King Bar", shortName: "recipe_monkey_king_bar" },
  135: { displayName: "Monkey King Bar", shortName: "monkey_king_bar" },
  136: { displayName: "Recipe Radiance", shortName: "recipe_radiance" },
  137: { displayName: "Radiance", shortName: "radiance" },
  138: { displayName: "Recipe Butterfly", shortName: "recipe_butterfly" },
  139: { displayName: "Butterfly", shortName: "butterfly" },
  140: { displayName: "Recipe Greater Crit", shortName: "recipe_greater_crit" },
  141: { displayName: "Greater Crit", shortName: "greater_crit" },
  142: { displayName: "Recipe Basher", shortName: "recipe_basher" },
  143: { displayName: "Basher", shortName: "basher" },
  144: { displayName: "Recipe Bfury", shortName: "recipe_bfury" },
  145: { displayName: "Bfury", shortName: "bfury" },
  146: { displayName: "Recipe Manta", shortName: "recipe_manta" },
  147: { displayName: "Manta", shortName: "manta" },
  148: { displayName: "Recipe Lesser Crit", shortName: "recipe_lesser_crit" },
  149: { displayName: "Lesser Crit", shortName: "lesser_crit" },
  150: { displayName: "Recipe Armlet", shortName: "recipe_armlet" },
  151: { displayName: "Armlet", shortName: "armlet" },
  152: { displayName: "Invis Sword", shortName: "invis_sword" },
  153: { displayName: "Recipe Sange And Yasha", shortName: "recipe_sange_and_yasha" },
  154: { displayName: "Sange And Yasha", shortName: "sange_and_yasha" },
  155: { displayName: "Recipe Satanic", shortName: "recipe_satanic" },
  156: { displayName: "Satanic", shortName: "satanic" },
  157: { displayName: "Recipe Mjollnir", shortName: "recipe_mjollnir" },
  158: { displayName: "Mjollnir", shortName: "mjollnir" },
  159: { displayName: "Recipe Skadi", shortName: "recipe_skadi" },
  160: { displayName: "Skadi", shortName: "skadi" },
  161: { displayName: "Recipe Sange", shortName: "recipe_sange" },
  162: { displayName: "Sange", shortName: "sange" },
  163: { displayName: "Recipe Helm Of The Dominator", shortName: "recipe_helm_of_the_dominator" },
  164: { displayName: "Helm Of The Dominator", shortName: "helm_of_the_dominator" },
  165: { displayName: "Recipe Maelstrom", shortName: "recipe_maelstrom" },
  166: { displayName: "Maelstrom", shortName: "maelstrom" },
  167: { displayName: "Recipe Desolator", shortName: "recipe_desolator" },
  168: { displayName: "Desolator", shortName: "desolator" },
  169: { displayName: "Recipe Yasha", shortName: "recipe_yasha" },
  170: { displayName: "Yasha", shortName: "yasha" },
  171: { displayName: "Recipe Mask Of Madness", shortName: "recipe_mask_of_madness" },
  172: { displayName: "Mask Of Madness", shortName: "mask_of_madness" },
  173: { displayName: "Recipe Diffusal Blade", shortName: "recipe_diffusal_blade" },
  174: { displayName: "Diffusal Blade", shortName: "diffusal_blade" },
  175: { displayName: "Recipe Ethereal Blade", shortName: "recipe_ethereal_blade" },
  176: { displayName: "Ethereal Blade", shortName: "ethereal_blade" },
  177: { displayName: "Recipe Soul Ring", shortName: "recipe_soul_ring" },
  178: { displayName: "Soul Ring", shortName: "soul_ring" },
  179: { displayName: "Recipe Arcane Boots", shortName: "recipe_arcane_boots" },
  180: { displayName: "Arcane Boots", shortName: "arcane_boots" },
  181: { displayName: "Orb Of Venom", shortName: "orb_of_venom" },
  182: { displayName: "Stout Shield", shortName: "stout_shield" },
  183: { displayName: "Recipe Invis Sword", shortName: "recipe_invis_sword" },
  184: { displayName: "Recipe Ancient Janggo", shortName: "recipe_ancient_janggo" },
  185: { displayName: "Ancient Janggo", shortName: "ancient_janggo" },
  186: { displayName: "Recipe Medallion Of Courage", shortName: "recipe_medallion_of_courage" },
  187: { displayName: "Medallion Of Courage", shortName: "medallion_of_courage" },
  188: { displayName: "Smoke Of Deceit", shortName: "smoke_of_deceit" },
  189: { displayName: "Recipe Veil Of Discord", shortName: "recipe_veil_of_discord" },
  190: { displayName: "Veil Of Discord", shortName: "veil_of_discord" },
  191: { displayName: "Recipe Necronomicon 2", shortName: "recipe_necronomicon_2" },
  192: { displayName: "Recipe Necronomicon 3", shortName: "recipe_necronomicon_3" },
  193: { displayName: "Necronomicon 2", shortName: "necronomicon_2" },
  194: { displayName: "Necronomicon 3", shortName: "necronomicon_3" },
  195: { displayName: "Recipe Diffusal Blade 2", shortName: "recipe_diffusal_blade_2" },
  196: { displayName: "Diffusal Blade 2", shortName: "diffusal_blade_2" },
  197: { displayName: "Recipe Dagon 2", shortName: "recipe_dagon_2" },
  198: { displayName: "Recipe Dagon 3", shortName: "recipe_dagon_3" },
  199: { displayName: "Recipe Dagon 4", shortName: "recipe_dagon_4" },
  200: { displayName: "Recipe Dagon 5", shortName: "recipe_dagon_5" },
  201: { displayName: "Dagon 2", shortName: "dagon_2" },
  202: { displayName: "Dagon 3", shortName: "dagon_3" },
  203: { displayName: "Dagon 4", shortName: "dagon_4" },
  204: { displayName: "Dagon 5", shortName: "dagon_5" },
  205: { displayName: "Recipe Rod Of Atos", shortName: "recipe_rod_of_atos" },
  206: { displayName: "Rod Of Atos", shortName: "rod_of_atos" },
  207: { displayName: "Recipe Abyssal Blade", shortName: "recipe_abyssal_blade" },
  208: { displayName: "Abyssal Blade", shortName: "abyssal_blade" },
  209: { displayName: "Recipe Heavens Halberd", shortName: "recipe_heavens_halberd" },
  210: { displayName: "Heavens Halberd", shortName: "heavens_halberd" },
  211: { displayName: "Recipe Ring Of Aquila", shortName: "recipe_ring_of_aquila" },
  212: { displayName: "Ring Of Aquila", shortName: "ring_of_aquila" },
  213: { displayName: "Recipe Tranquil Boots", shortName: "recipe_tranquil_boots" },
  214: { displayName: "Tranquil Boots", shortName: "tranquil_boots" },
  215: { displayName: "Shadow Amulet", shortName: "shadow_amulet" },
  216: { displayName: "Enchanted Mango", shortName: "enchanted_mango" },
  217: { displayName: "Recipe Ward Dispenser", shortName: "recipe_ward_dispenser" },
  218: { displayName: "Ward Dispenser", shortName: "ward_dispenser" },
  219: { displayName: "Recipe Travel Boots 2", shortName: "recipe_travel_boots_2" },
  220: { displayName: "Travel Boots 2", shortName: "travel_boots_2" },
  221: { displayName: "Recipe Lotus Orb", shortName: "recipe_lotus_orb" },
  222: { displayName: "Recipe Meteor Hammer", shortName: "recipe_meteor_hammer" },
  223: { displayName: "Meteor Hammer", shortName: "meteor_hammer" },
  224: { displayName: "Recipe Nullifier", shortName: "recipe_nullifier" },
  225: { displayName: "Nullifier", shortName: "nullifier" },
  226: { displayName: "Lotus Orb", shortName: "lotus_orb" },
  227: { displayName: "Recipe Solar Crest", shortName: "recipe_solar_crest" },
  228: { displayName: "Recipe Octarine Core", shortName: "recipe_octarine_core" },
  229: { displayName: "Solar Crest", shortName: "solar_crest" },
  230: { displayName: "Recipe Guardian Greaves", shortName: "recipe_guardian_greaves" },
  231: { displayName: "Guardian Greaves", shortName: "guardian_greaves" },
  232: { displayName: "Aether Lens", shortName: "aether_lens" },
  233: { displayName: "Recipe Aether Lens", shortName: "recipe_aether_lens" },
  234: { displayName: "Recipe Dragon Lance", shortName: "recipe_dragon_lance" },
  235: { displayName: "Octarine Core", shortName: "octarine_core" },
  236: { displayName: "Dragon Lance", shortName: "dragon_lance" },
  237: { displayName: "Faerie Fire", shortName: "faerie_fire" },
  238: { displayName: "Recipe Iron Talon", shortName: "recipe_iron_talon" },
  239: { displayName: "Iron Talon", shortName: "iron_talon" },
  240: { displayName: "Blight Stone", shortName: "blight_stone" },
  241: { displayName: "Tango Single", shortName: "tango_single" },
  242: { displayName: "Crimson Guard", shortName: "crimson_guard" },
  243: { displayName: "Recipe Crimson Guard", shortName: "recipe_crimson_guard" },
  244: { displayName: "Wind Lace", shortName: "wind_lace" },
  245: { displayName: "Recipe Bloodthorn", shortName: "recipe_bloodthorn" },
  246: { displayName: "Recipe Moon Shard", shortName: "recipe_moon_shard" },
  247: { displayName: "Moon Shard", shortName: "moon_shard" },
  248: { displayName: "Recipe Silver Edge", shortName: "recipe_silver_edge" },
  249: { displayName: "Silver Edge", shortName: "silver_edge" },
  250: { displayName: "Bloodthorn", shortName: "bloodthorn" },
  251: { displayName: "Recipe Echo Sabre", shortName: "recipe_echo_sabre" },
  252: { displayName: "Echo Sabre", shortName: "echo_sabre" },
  253: { displayName: "Recipe Glimmer Cape", shortName: "recipe_glimmer_cape" },
  254: { displayName: "Glimmer Cape", shortName: "glimmer_cape" },
  255: { displayName: "Recipe Aeon Disk", shortName: "recipe_aeon_disk" },
  256: { displayName: "Aeon Disk", shortName: "aeon_disk" },
  257: { displayName: "Tome Of Knowledge", shortName: "tome_of_knowledge" },
  258: { displayName: "Recipe Kaya", shortName: "recipe_kaya" },
  259: { displayName: "Kaya", shortName: "kaya" },
  260: { displayName: "Refresher Shard", shortName: "refresher_shard" },
  261: { displayName: "Crown", shortName: "crown" },
  262: { displayName: "Recipe Hurricane Pike", shortName: "recipe_hurricane_pike" },
  263: { displayName: "Hurricane Pike", shortName: "hurricane_pike" },
  265: { displayName: "Infused Raindrop", shortName: "infused_raindrop" },
  266: { displayName: "Recipe Spirit Vessel", shortName: "recipe_spirit_vessel" },
  267: { displayName: "Spirit Vessel", shortName: "spirit_vessel" },
  268: { displayName: "Recipe Holy Locket", shortName: "recipe_holy_locket" },
  269: { displayName: "Holy Locket", shortName: "holy_locket" },
  270: { displayName: "Recipe Ultimate Scepter 2", shortName: "recipe_ultimate_scepter_2" },
  271: { displayName: "Ultimate Scepter 2", shortName: "ultimate_scepter_2" },
  272: { displayName: "Recipe Kaya And Sange", shortName: "recipe_kaya_and_sange" },
  273: { displayName: "Kaya And Sange", shortName: "kaya_and_sange" },
  274: { displayName: "Recipe Yasha And Kaya", shortName: "recipe_yasha_and_kaya" },
  275: { displayName: "Recipe Trident", shortName: "recipe_trident" },
  276: { displayName: "Combo Breaker", shortName: "combo_breaker" },
  277: { displayName: "Yasha And Kaya", shortName: "yasha_and_kaya" },
  279: { displayName: "Ring Of Tarrasque", shortName: "ring_of_tarrasque" },
  286: { displayName: "Flying Courier", shortName: "flying_courier" },
  287: { displayName: "Keen Optic", shortName: "keen_optic" },
  288: { displayName: "Grove Bow", shortName: "grove_bow" },
  289: { displayName: "Quickening Charm", shortName: "quickening_charm" },
  290: { displayName: "Philosophers Stone", shortName: "philosophers_stone" },
  291: { displayName: "Force Boots", shortName: "force_boots" },
  292: { displayName: "Desolator 2", shortName: "desolator_2" },
  293: { displayName: "Phoenix Ash", shortName: "phoenix_ash" },
  294: { displayName: "Seer Stone", shortName: "seer_stone" },
  295: { displayName: "Greater Mango", shortName: "greater_mango" },
  297: { displayName: "Vampire Fangs", shortName: "vampire_fangs" },
  298: { displayName: "Craggy Coat", shortName: "craggy_coat" },
  299: { displayName: "Greater Faerie Fire", shortName: "greater_faerie_fire" },
  300: { displayName: "Timeless Relic", shortName: "timeless_relic" },
  301: { displayName: "Mirror Shield", shortName: "mirror_shield" },
  302: { displayName: "Elixer", shortName: "elixer" },
  303: { displayName: "Recipe Ironwood Tree", shortName: "recipe_ironwood_tree" },
  304: { displayName: "Ironwood Tree", shortName: "ironwood_tree" },
  305: { displayName: "Royal Jelly", shortName: "royal_jelly" },
  306: { displayName: "Pupils Gift", shortName: "pupils_gift" },
  307: { displayName: "Tome Of Aghanim", shortName: "tome_of_aghanim" },
  308: { displayName: "Repair Kit", shortName: "repair_kit" },
  309: { displayName: "Mind Breaker", shortName: "mind_breaker" },
  310: { displayName: "Third Eye", shortName: "third_eye" },
  311: { displayName: "Spell Prism", shortName: "spell_prism" },
  312: { displayName: "Horizon", shortName: "horizon" },
  313: { displayName: "Fusion Rune", shortName: "fusion_rune" },
  317: { displayName: "Recipe Fallen Sky", shortName: "recipe_fallen_sky" },
  325: { displayName: "Princes Knife", shortName: "princes_knife" },
  326: { displayName: "Spider Legs", shortName: "spider_legs" },
  327: { displayName: "Helm Of The Undying", shortName: "helm_of_the_undying" },
  328: { displayName: "Mango Tree", shortName: "mango_tree" },
  329: { displayName: "Recipe Vambrace", shortName: "recipe_vambrace" },
  330: { displayName: "Witless Shako", shortName: "witless_shako" },
  331: { displayName: "Vambrace", shortName: "vambrace" },
  334: { displayName: "Imp Claw", shortName: "imp_claw" },
  335: { displayName: "Flicker", shortName: "flicker" },
  336: { displayName: "Spy Gadget", shortName: "spy_gadget" },
  349: { displayName: "Arcane Ring", shortName: "arcane_ring" },
  354: { displayName: "Ocean Heart", shortName: "ocean_heart" },
  355: { displayName: "Broom Handle", shortName: "broom_handle" },
  356: { displayName: "Trusty Shovel", shortName: "trusty_shovel" },
  357: { displayName: "Nether Shawl", shortName: "nether_shawl" },
  358: { displayName: "Dragon Scale", shortName: "dragon_scale" },
  359: { displayName: "Essence Ring", shortName: "essence_ring" },
  360: { displayName: "Clumsy Net", shortName: "clumsy_net" },
  361: { displayName: "Enchanted Quiver", shortName: "enchanted_quiver" },
  362: { displayName: "Ninja Gear", shortName: "ninja_gear" },
  363: { displayName: "Illusionsts Cape", shortName: "illusionsts_cape" },
  364: { displayName: "Havoc Hammer", shortName: "havoc_hammer" },
  365: { displayName: "Panic Button", shortName: "panic_button" },
  366: { displayName: "Apex", shortName: "apex" },
  367: { displayName: "Ballista", shortName: "ballista" },
  368: { displayName: "Woodland Striders", shortName: "woodland_striders" },
  369: { displayName: "Trident", shortName: "trident" },
  370: { displayName: "Demonicon", shortName: "demonicon" },
  371: { displayName: "Fallen Sky", shortName: "fallen_sky" },
  372: { displayName: "Pirate Hat", shortName: "pirate_hat" },
  373: { displayName: "Dimensional Doorway", shortName: "dimensional_doorway" },
  374: { displayName: "Ex Machina", shortName: "ex_machina" },
  375: { displayName: "Faded Broach", shortName: "faded_broach" },
  376: { displayName: "Paladin Sword", shortName: "paladin_sword" },
  377: { displayName: "Minotaur Horn", shortName: "minotaur_horn" },
  378: { displayName: "Orb Of Destruction", shortName: "orb_of_destruction" },
  379: { displayName: "The Leveller", shortName: "the_leveller" },
  381: { displayName: "Titan Sliver", shortName: "titan_sliver" },
  473: { displayName: "Voodoo Mask", shortName: "voodoo_mask" },
  485: { displayName: "Blitz Knuckles", shortName: "blitz_knuckles" },
  533: { displayName: "Recipe Witch Blade", shortName: "recipe_witch_blade" },
  534: { displayName: "Witch Blade", shortName: "witch_blade" },
  565: { displayName: "Chipped Vest", shortName: "chipped_vest" },
  566: { displayName: "Wizard Glass", shortName: "wizard_glass" },
  569: { displayName: "Orb Of Corrosion", shortName: "orb_of_corrosion" },
  570: { displayName: "Gloves Of Travel", shortName: "gloves_of_travel" },
  571: { displayName: "Trickster Cloak", shortName: "trickster_cloak" },
  573: { displayName: "Elven Tunic", shortName: "elven_tunic" },
  574: { displayName: "Cloak Of Flames", shortName: "cloak_of_flames" },
  575: { displayName: "Venom Gland", shortName: "venom_gland" },
  576: { displayName: "Gladiator Helm", shortName: "gladiator_helm" },
  577: { displayName: "Possessed Mask", shortName: "possessed_mask" },
  578: { displayName: "Ancient Perseverance", shortName: "ancient_perseverance" },
  582: { displayName: "Oakheart", shortName: "oakheart" },
  585: { displayName: "Stormcrafter", shortName: "stormcrafter" },
  588: { displayName: "Overflowing Elixir", shortName: "overflowing_elixir" },
  589: { displayName: "Mysterious Hat", shortName: "mysterious_hat" },
  593: { displayName: "Fluffy Hat", shortName: "fluffy_hat" },
  596: { displayName: "Falcon Blade", shortName: "falcon_blade" },
  597: { displayName: "Recipe Mage Slayer", shortName: "recipe_mage_slayer" },
  598: { displayName: "Mage Slayer", shortName: "mage_slayer" },
  599: { displayName: "Recipe Falcon Blade", shortName: "recipe_falcon_blade" },
  600: { displayName: "Overwhelming Blink", shortName: "overwhelming_blink" },
  603: { displayName: "Swift Blink", shortName: "swift_blink" },
  604: { displayName: "Arcane Blink", shortName: "arcane_blink" },
  606: { displayName: "Recipe Arcane Blink", shortName: "recipe_arcane_blink" },
  607: { displayName: "Recipe Swift Blink", shortName: "recipe_swift_blink" },
  608: { displayName: "Recipe Overwhelming Blink", shortName: "recipe_overwhelming_blink" },
  609: { displayName: "Aghanims Shard", shortName: "aghanims_shard" },
  610: { displayName: "Wind Waker", shortName: "wind_waker" },
  612: { displayName: "Recipe Wind Waker", shortName: "recipe_wind_waker" },
  633: { displayName: "Recipe Helm Of The Overlord", shortName: "recipe_helm_of_the_overlord" },
  635: { displayName: "Helm Of The Overlord", shortName: "helm_of_the_overlord" },
  637: { displayName: "Star Mace", shortName: "star_mace" },
  638: { displayName: "Penta Edged Sword", shortName: "penta_edged_sword" },
  640: { displayName: "Recipe Orb Of Corrosion", shortName: "recipe_orb_of_corrosion" },
  653: { displayName: "Recipe Grandmasters Glaive", shortName: "recipe_grandmasters_glaive" },
  655: { displayName: "Grandmasters Glaive", shortName: "grandmasters_glaive" },
  674: { displayName: "Warhammer", shortName: "warhammer" },
  675: { displayName: "Psychic Headband", shortName: "psychic_headband" },
  676: { displayName: "Ceremonial Robe", shortName: "ceremonial_robe" },
  677: { displayName: "Book Of Shadows", shortName: "book_of_shadows" },
  678: { displayName: "Giants Ring", shortName: "giants_ring" },
  679: { displayName: "Vengeances Shadow", shortName: "vengeances_shadow" },
  680: { displayName: "Bullwhip", shortName: "bullwhip" },
  686: { displayName: "Quicksilver Amulet", shortName: "quicksilver_amulet" },
  691: { displayName: "Recipe Eternal Shroud", shortName: "recipe_eternal_shroud" },
  692: { displayName: "Eternal Shroud", shortName: "eternal_shroud" },
  725: { displayName: "Aghanims Shard Roshan", shortName: "aghanims_shard_roshan" },
  727: { displayName: "Ultimate Scepter Roshan", shortName: "ultimate_scepter_roshan" },
  731: { displayName: "Satchel", shortName: "satchel" },
  824: { displayName: "Assassins Dagger", shortName: "assassins_dagger" },
  825: { displayName: "Ascetic Cap", shortName: "ascetic_cap" },
  826: { displayName: "Sample Picker", shortName: "sample_picker" },
  827: { displayName: "Icarus Wings", shortName: "icarus_wings" },
  828: { displayName: "Misericorde", shortName: "misericorde" },
  829: { displayName: "Force Field", shortName: "force_field" },
  833: { displayName: "Recipe Tenderizer", shortName: "recipe_tenderizer" },
  834: { displayName: "Black Powder Bag", shortName: "black_powder_bag" },
  835: { displayName: "Paintball", shortName: "paintball" },
  836: { displayName: "Light Robes", shortName: "light_robes" },
  837: { displayName: "Heavy Blade", shortName: "heavy_blade" },
  838: { displayName: "Unstable Wand", shortName: "unstable_wand" },
  839: { displayName: "Fortitude Ring", shortName: "fortitude_ring" },
  840: { displayName: "Pogo Stick", shortName: "pogo_stick" },
  849: { displayName: "Mechanical Arm", shortName: "mechanical_arm" },
  859: { displayName: "Recipe Voidwalker Scythe", shortName: "recipe_voidwalker_scythe" },
  904: { displayName: "Voidwalker Scythe", shortName: "voidwalker_scythe" },
  906: { displayName: "Tenderizer", shortName: "tenderizer" },
  907: { displayName: "Recipe Wraith Pact", shortName: "recipe_wraith_pact" },
  908: { displayName: "Wraith Pact", shortName: "wraith_pact" },
  910: { displayName: "Recipe Revenants Brooch", shortName: "recipe_revenants_brooch" },
  911: { displayName: "Revenants Brooch", shortName: "revenants_brooch" },
  928: { displayName: "Recipe Eagle Eye", shortName: "recipe_eagle_eye" },
  929: { displayName: "Eagle Eye", shortName: "eagle_eye" },
  930: { displayName: "Recipe Boots Of Bearing", shortName: "recipe_boots_of_bearing" },
  931: { displayName: "Boots Of Bearing", shortName: "boots_of_bearing" },
  938: { displayName: "Slime Vial", shortName: "slime_vial" },
  939: { displayName: "Harpoon", shortName: "harpoon" },
  940: { displayName: "Wand Of The Brine", shortName: "wand_of_the_brine" },
  945: { displayName: "Seeds Of Serenity", shortName: "seeds_of_serenity" },
  946: { displayName: "Lance Of Pursuit", shortName: "lance_of_pursuit" },
  947: { displayName: "Occult Bracelet", shortName: "occult_bracelet" },
  948: { displayName: "Tome Of Omniscience", shortName: "tome_of_omniscience" },
  949: { displayName: "Ogre Seal Totem", shortName: "ogre_seal_totem" },
  950: { displayName: "Defiant Shell", shortName: "defiant_shell" },
  964: { displayName: "Diffusal Blade 2", shortName: "diffusal_blade_2" },
  965: { displayName: "Recipe Diffusal Blade 2", shortName: "recipe_diffusal_blade_2" },
  968: { displayName: "Arcane Scout", shortName: "arcane_scout" },
  969: { displayName: "Barricade", shortName: "barricade" },
  990: { displayName: "Eye Of The Vizier", shortName: "eye_of_the_vizier" },
  998: { displayName: "Manacles Of Power", shortName: "manacles_of_power" },
  1000: { displayName: "Bottomless Chalice", shortName: "bottomless_chalice" },
  1017: { displayName: "Wand Of Sanctitude", shortName: "wand_of_sanctitude" },
  1021: { displayName: "River Painter", shortName: "river_painter" },
  1022: { displayName: "River Painter2", shortName: "river_painter2" },
  1023: { displayName: "River Painter3", shortName: "river_painter3" },
  1024: { displayName: "River Painter4", shortName: "river_painter4" },
  1025: { displayName: "River Painter5", shortName: "river_painter5" },
  1026: { displayName: "River Painter6", shortName: "river_painter6" },
  1027: { displayName: "River Painter7", shortName: "river_painter7" },
  1028: { displayName: "Mutation Tombstone", shortName: "mutation_tombstone" },
  1029: { displayName: "Super Blink", shortName: "super_blink" },
  1030: { displayName: "Pocket Tower", shortName: "pocket_tower" },
  1032: { displayName: "Pocket Roshan", shortName: "pocket_roshan" },
  1076: { displayName: "Specialists Array", shortName: "specialists_array" },
  1077: { displayName: "Dagger Of Ristul", shortName: "dagger_of_ristul" },
  1090: { displayName: "Muertas Gun", shortName: "muertas_gun" },
  1091: { displayName: "Samurai Tabi", shortName: "samurai_tabi" },
  1092: { displayName: "Recipe Hermes Sandals", shortName: "recipe_hermes_sandals" },
  1093: { displayName: "Hermes Sandals", shortName: "hermes_sandals" },
  1094: { displayName: "Recipe Lunar Crest", shortName: "recipe_lunar_crest" },
  1095: { displayName: "Lunar Crest", shortName: "lunar_crest" },
  1096: { displayName: "Recipe Disperser", shortName: "recipe_disperser" },
  1097: { displayName: "Disperser", shortName: "disperser" },
  1098: { displayName: "Recipe Samurai Tabi", shortName: "recipe_samurai_tabi" },
  1099: { displayName: "Recipe Witches Switch", shortName: "recipe_witches_switch" },
  1100: { displayName: "Witches Switch", shortName: "witches_switch" },
  1101: { displayName: "Recipe Harpoon", shortName: "recipe_harpoon" },
  1106: { displayName: "Recipe Phylactery", shortName: "recipe_phylactery" },
  1107: { displayName: "Phylactery", shortName: "phylactery" },
  1122: { displayName: "Diadem", shortName: "diadem" },
  1123: { displayName: "Blood Grenade", shortName: "blood_grenade" },
  1124: { displayName: "Spark Of Courage", shortName: "spark_of_courage" },
  1125: { displayName: "Cornucopia", shortName: "cornucopia" },
  1127: { displayName: "Recipe Pavise", shortName: "recipe_pavise" },
  1128: { displayName: "Pavise", shortName: "pavise" },
  1154: { displayName: "Royale With Cheese", shortName: "royale_with_cheese" },
  1156: { displayName: "Ancient Guardian", shortName: "ancient_guardian" },
  1157: { displayName: "Safety Bubble", shortName: "safety_bubble" },
  1158: { displayName: "Whisper Of The Dread", shortName: "whisper_of_the_dread" },
  1159: { displayName: "Nemesis Curse", shortName: "nemesis_curse" },
  1160: { displayName: "Avianas Feather", shortName: "avianas_feather" },
  1161: { displayName: "Unwavering Condition", shortName: "unwavering_condition" },
  1163: { displayName: "Recipe Aetherial Halo", shortName: "recipe_aetherial_halo" },
  1164: { displayName: "Aetherial Halo", shortName: "aetherial_halo" },
  1167: { displayName: "Light Collector", shortName: "light_collector" },
  1168: { displayName: "Rattlecage", shortName: "rattlecage" },
  1440: { displayName: "Black Grimoire", shortName: "black_grimoire" },
  1441: { displayName: "Grisgris", shortName: "grisgris" },
  1466: { displayName: "Gungir", shortName: "gungir" },
  1565: { displayName: "Recipe Gungir", shortName: "recipe_gungir" },
  1575: { displayName: "Orb Of Frost", shortName: "orb_of_frost" },
  1576: { displayName: "Enhancement Vast", shortName: "enhancement_vast" },
  1577: { displayName: "Enhancement Quickened", shortName: "enhancement_quickened" },
  1578: { displayName: "Cursed Circlet", shortName: "cursed_circlet" },
  1579: { displayName: "Ogre Heart", shortName: "ogre_heart" },
  1580: { displayName: "Neutral Tabi", shortName: "neutral_tabi" },
  1581: { displayName: "Enhancement Audacious", shortName: "enhancement_audacious" },
  1582: { displayName: "Hellbear Totem", shortName: "hellbear_totem" },
  1583: { displayName: "Enhancement Mystical", shortName: "enhancement_mystical" },
  1584: { displayName: "Enhancement Alert", shortName: "enhancement_alert" },
  1585: { displayName: "Enhancement Brawny", shortName: "enhancement_brawny" },
  1586: { displayName: "Enhancement Tough", shortName: "enhancement_tough" },
  1587: { displayName: "Enhancement Feverish", shortName: "enhancement_feverish" },
  1588: { displayName: "Enhancement Fleetfooted", shortName: "enhancement_fleetfooted" },
  1589: { displayName: "Enhancement Crude", shortName: "enhancement_crude" },
  1590: { displayName: "Enhancement Boundless", shortName: "enhancement_boundless" },
  1591: { displayName: "Enhancement Wise", shortName: "enhancement_wise" },
  1592: { displayName: "Enhancement Timeless", shortName: "enhancement_timeless" },
  1593: { displayName: "Enhancement Greedy", shortName: "enhancement_greedy" },
  1594: { displayName: "Enhancement Vampiric", shortName: "enhancement_vampiric" },
  1595: { displayName: "Enhancement Keen Eyed", shortName: "enhancement_keen_eyed" },
  1596: { displayName: "Enhancement Evolved", shortName: "enhancement_evolved" },
  1597: { displayName: "Enhancement Titanic", shortName: "enhancement_titanic" },
  1598: { displayName: "Unrelenting Eye", shortName: "unrelenting_eye" },
  1599: { displayName: "Mana Draught", shortName: "mana_draught" },
  1600: { displayName: "Rippers Lash", shortName: "rippers_lash" },
  1601: { displayName: "Crippling Crossbow", shortName: "crippling_crossbow" },
  1602: { displayName: "Gale Guard", shortName: "gale_guard" },
  1603: { displayName: "Gunpowder Gauntlets", shortName: "gunpowder_gauntlets" },
  1604: { displayName: "Searing Signet", shortName: "searing_signet" },
  1605: { displayName: "Serrated Shiv", shortName: "serrated_shiv" },
  1606: { displayName: "Polliwog Charm", shortName: "polliwog_charm" },
  1607: { displayName: "Magnifying Monocle", shortName: "magnifying_monocle" },
  1608: { displayName: "Pyrrhic Cloak", shortName: "pyrrhic_cloak" },
  1609: { displayName: "Madstone Bundle", shortName: "madstone_bundle" },
  1610: { displayName: "Miniboss Minion Summoner", shortName: "miniboss_minion_summoner" },
  1636: { displayName: "Crystal Raindrop", shortName: "crystal_raindrop" },
  1637: { displayName: "Kobold Cup", shortName: "kobold_cup" },
  1638: { displayName: "Dormant Curio", shortName: "dormant_curio" },
  1639: { displayName: "Sisters Shroud", shortName: "sisters_shroud" },
  1640: { displayName: "Jidi Pollen Bag", shortName: "jidi_pollen_bag" },
  1641: { displayName: "Outworld Staff", shortName: "outworld_staff" },
  1642: { displayName: "Dezun Bloodrite", shortName: "dezun_bloodrite" },
  1643: { displayName: "Giant Maul", shortName: "giant_maul" },
  1644: { displayName: "Divine Regalia", shortName: "divine_regalia" },
  1645: { displayName: "Divine Regalia Broken", shortName: "divine_regalia_broken" },
  1646: { displayName: "Circlet Of The Flayed Twins", shortName: "circlet_of_the_flayed_twins" },
  1647: { displayName: "Enhancement Fierce", shortName: "enhancement_fierce" },
  1648: { displayName: "Enhancement Dominant", shortName: "enhancement_dominant" },
  1649: { displayName: "Enhancement Restorative", shortName: "enhancement_restorative" },
  1650: { displayName: "Enhancement Thick", shortName: "enhancement_thick" },
  1651: { displayName: "Enhancement Curious", shortName: "enhancement_curious" },
  1652: { displayName: "Furion Gold Bag", shortName: "furion_gold_bag" },
  1715: { displayName: "Recipe Specialists Array", shortName: "recipe_specialists_array" },
  1716: { displayName: "Weighted Dice", shortName: "weighted_dice" },
  1717: { displayName: "Ash Legion Shield", shortName: "ash_legion_shield" },
  1718: { displayName: "Riftshadow Prism", shortName: "riftshadow_prism" },
  1719: { displayName: "Metamorphic Mandible", shortName: "metamorphic_mandible" },
  1720: { displayName: "Idol Of Screeauk", shortName: "idol_of_screeauk" },
  1721: { displayName: "Flayers Bota", shortName: "flayers_bota" },
  1800: { displayName: "Recipe Caster Rapier", shortName: "recipe_caster_rapier" },
  1801: { displayName: "Caster Rapier", shortName: "caster_rapier" },
  1802: { displayName: "Tiara Of Selemene", shortName: "tiara_of_selemene" },
  1803: { displayName: "Doubloon", shortName: "doubloon" },
  1804: { displayName: "Roshans Banner", shortName: "roshans_banner" },
  1805: { displayName: "Recipe Devastator", shortName: "recipe_devastator" },
  1806: { displayName: "Devastator", shortName: "devastator" },
  1807: { displayName: "Recipe Angels Demise", shortName: "recipe_angels_demise" },
  1808: { displayName: "Angels Demise", shortName: "angels_demise" },
  2091: { displayName: "Tier1 Token", shortName: "tier1_token" },
  2092: { displayName: "Tier2 Token", shortName: "tier2_token" },
  2093: { displayName: "Tier3 Token", shortName: "tier3_token" },
  2094: { displayName: "Tier4 Token", shortName: "tier4_token" },
  2095: { displayName: "Tier5 Token", shortName: "tier5_token" },
  2096: { displayName: "Vindicators Axe", shortName: "vindicators_axe" },
  2097: { displayName: "Duelist Gloves", shortName: "duelist_gloves" },
  2098: { displayName: "Horizons Equilibrium", shortName: "horizons_equilibrium" },
  2099: { displayName: "Blighted Spirit", shortName: "blighted_spirit" },
  2190: { displayName: "Dandelion Amulet", shortName: "dandelion_amulet" },
  2191: { displayName: "Turtle Shell", shortName: "turtle_shell" },
  2192: { displayName: "Martyrs Plate", shortName: "martyrs_plate" },
  2193: { displayName: "Gossamer Cape", shortName: "gossamer_cape" },
  4204: { displayName: "Famango", shortName: "famango" },
  4205: { displayName: "Great Famango", shortName: "great_famango" },
  4206: { displayName: "Greater Famango", shortName: "greater_famango" },
  4207: { displayName: "Recipe Great Famango", shortName: "recipe_great_famango" },
  4208: { displayName: "Recipe Greater Famango", shortName: "recipe_greater_famango" },
  4300: { displayName: "Ofrenda", shortName: "ofrenda" },
  4301: { displayName: "Ofrenda Shovel", shortName: "ofrenda_shovel" },
  4302: { displayName: "Ofrenda Pledge", shortName: "ofrenda_pledge" },
};

export function getItemName(itemId: number): string {
  return ITEMS[itemId]?.displayName ?? `Item #${itemId}`;
}

export function itemIconUrl(itemId: number): string | null {
  const shortName = ITEMS[itemId]?.shortName;
  if (!shortName) return null;
  return `https://cdn.stratz.com/images/dota2/items/${shortName}.png`;
}
